/* Expert Availability Create*/
export const REQUEST_CREATE_EXPERT_AVAILABILITY_UPDATE =
  "REQUEST_CREATE_EXPERT_AVAILABILITY_UPDATE";
export const RECEIVE_CREATE_EXPERT_AVAILABILITY_UPDATE =
  "RECEIVE_CREATE_EXPERT_AVAILABILITY_UPDATE";
export const EXPERT_AVAILABILITY_UPDATE_CREATE_ERROR =
  "EXPERT_AVAILABILITY_UPDATE_CREATE_ERROR";

/**
 * Table
 */
export const REQUEST_TABLE_LIST = "REQUEST_TABLE_LIST";
export const RECEIVE_TABLE_LIST = "RECEIVE_TABLE_LIST";
export const FETCH_TABLE_LIST_FAIL = "FETCH_TABLE_LIST_FAIL";
export const SET_TABLE_PAGE = "SET_TABLE_PAGE";
export const CLEAR_TABLE_LIST = "CLEAR_TABLE_LIST";

/* Dashboard */
export const REQUEST_DASHBOARD_COUNT = "REQUEST_DASHBOARD_COUNT";
export const RECEIVE_DASHBOARD_COUNT = "RECEIVE_DASHBOARD_COUNT";
export const FETCH_DASHBOARDD_COUNT_FAIL = "FETCH_DASHBOARDD_COUNT_FAIL";

/* Landing Page */
export const REQUEST_LANDING_PAGE_DETAIL = "REQUEST_LANDING_PAGE_DETAIL";
export const RECEIVE_LANDING_PAGE_DETAIL = "RECEIVE_LANDING_PAGE_DETAIL";
export const FETCH_LANDING_PAGE_DETAIL_FAIL = "FETCH_LANDING_PAGE_DETAIL_FAIL";

/* Delete Tags */
export const REQUEST_DELETE_TAG = "REQUEST_DELETE_TAG";
export const RECEIVE_DELETE_TAG = "RECEIVE_DELETE_TAG";
export const TAG_DELETE_ERROR = "TAG_DELETE_ERROR";

/* Add TAG */
export const REQUEST_CREATE_TAG = "REQUEST_CREATE_TAG";
export const RECEIVE_CREATE_TAG = "RECEIVE_CREATE_TAG";
export const TAG_CREATE_ERROR = "TAG_CREATE_ERROR";

/* Update TAG */
export const REQUEST_UPDATE_TAG = "REQUEST_UPDATE_TAG";
export const RECEIVE_UPDATE_TAG = "RECEIVE_UPDATE_TAG";
export const TAG_UPDATE_ERROR = "TAG_UPDATE_ERROR";

/* Add TAG */
export const REQUEST_CREATE_TAG_TYPE = "REQUEST_CREATE_TAG_TYPE";
export const RECEIVE_CREATE_TAG_TYPE = "RECEIVE_CREATE_TAG_TYPE";
export const TAG_TYPE_CREATE_ERROR = "TAG_TYPE_CREATE_ERROR";

/* Update TAG */
export const REQUEST_UPDATE_TAG_TYPE = "REQUEST_UPDATE_TAG_TYPE";
export const RECEIVE_UPDATE_TAG_TYPE = "RECEIVE_UPDATE_TAG_TYPE";
export const TAG_TYPE_UPDATE_ERROR = "TAG_TYPE_UPDATE_ERROR";

/* Delete Tag Types */
export const REQUEST_DELETE_TAG_TYPE = "REQUEST_DELETE_TAG_TYPE";
export const RECEIVE_DELETE_TAG_TYPE = "RECEIVE_DELETE_TAG_TYPE";
export const TAG_TYPE_DELETE_ERROR = "TAG_TYPE_DELETE_ERROR";

// Add Landing Page
export const REQUEST_CREATE_LANDING_PAGE = "REQUEST_CREATE_LANDING_PAGE";
export const RECEIVE_CREATE_LANDING_PAGE = "RECEIVE_CREATE_LANDING_PAGE";
export const LANDING_PAGE_CREATE_ERROR = "LANDING_PAGE_CREATE_ERROR";

/* Update Landing Page */
export const REQUEST_UPDATE_LANDING_PAGE = "REQUEST_UPDATE_LANDING_PAGE";
export const RECEIVE_UPDATE_LANDING_PAGE = "RECEIVE_UPDATE_LANDING_PAGE";
export const LANDING_PAGE_UPDATE_ERROR = "LANDING_PAGE_UPDATE_ERROR";

/* Delete Landing Page */
export const REQUEST_DELETE_LANDING_PAGE = "REQUEST_DELETE_LANDING_PAGE";
export const RECEIVE_DELETE_LANDING_PAGE = "RECEIVE_DELETE_LANDING_PAGE";
export const LANDING_PAGE_DELETE_ERROR = "LANDING_PAGE_DELETE_ERROR";

// Add Landing Page Block
export const REQUEST_CREATE_LANDING_PAGE_BLOCK =
  "REQUEST_CREATE_LANDING_PAGE_BLOCK";
export const RECEIVE_CREATE_LANDING_PAGE_BLOCK =
  "RECEIVE_CREATE_LANDING_PAGE_BLOCK";
export const LANDING_PAGE_BLOCK_CREATE_ERROR =
  "LANDING_PAGE_BLOCK_CREATE_ERROR";

/* Update Landing Page Block*/
export const REQUEST_UPDATE_LANDING_PAGE_BLOCK =
  "REQUEST_UPDATE_LANDING_PAGE_BLOCK";
export const RECEIVE_UPDATE_LANDING_PAGE_BLOCK =
  "RECEIVE_UPDATE_LANDING_PAGE_BLOCK";
export const LANDING_PAGE_BLOCK_UPDATE_ERROR =
  "LANDING_PAGE_BLOCK_UPDATE_ERROR";

/* Delete Landing Page Block*/
export const REQUEST_DELETE_LANDING_PAGE_BLOCK =
  "REQUEST_DELETE_LANDING_PAGE_BLOCK";
export const RECEIVE_DELETE_LANDING_PAGE_BLOCK =
  "RECEIVE_DELETE_LANDING_PAGE_BLOCK";
export const LANDING_PAGE_BLOCK_DELETE_ERROR =
  "LANDING_PAGE_BLOCK_DELETE_ERROR";

/* Update Expert Profile Tag */
export const REQUEST_UPDATE_EXPERT_PROFILE_TAG =
  "REQUEST_UPDATE_EXPERT_PROFILE_TAG";
export const RECEIVE_UPDATE_EXPERT_PROFILE_TAG =
  "RECEIVE_UPDATE_EXPERT_PROFILE_TAG";
export const EXPERT_PROFILE_TAG_UPDATE_ERROR =
  "EXPERT_PROFILE_TAG_UPDATE_ERROR";

/* Update Expert Status Update */
export const REQUEST_UPDATE_EXPERT = "REQUEST_UPDATE_EXPERT";
export const RECEIVE_UPDATE_EXPERT = "RECEIVE_UPDATE_EXPERT";
export const EXPERT_UPDATE_ERROR = "EXPERT_UPDATE_ERROR";

/* Update Project Status */
export const REQUEST_UPDATE_PROJECT = "REQUEST_UPDATE_PROJECT";
export const RECEIVE_UPDATE_PROJECT = "RECEIVE_UPDATE_PROJECT";
export const PROJECT_UPDATE_ERROR = "PROJECT_UPDATE_ERROR";

/* Add Project Category */
export const REQUEST_CREATE_PROJECT_CATEGORY =
  "REQUEST_CREATE_PROJECT_CATEGORY";
export const RECEIVE_CREATE_PROJECT_CATEGORY =
  "RECEIVE_CREATE_PROJECT_CATEGORY";
export const PROJECT_CATEGORY_CREATE_ERROR = "PROJECT_CATEGORY_CREATE_ERROR";

/* Update Project Category */
export const REQUEST_UPDATE_PROJECT_CATEGORY =
  "REQUEST_UPDATE_PROJECT_CATEGORY";
export const RECEIVE_UPDATE_PROJECT_CATEGORY =
  "RECEIVE_UPDATE_PROJECT_CATEGORY";
export const PROJECT_CATEGORY_UPDATE_ERROR = "PROJECT_CATEGORY_UPDATE_ERROR";

/* Delete Project Category */
export const REQUEST_DELETE_PROJECT_CATEGORY =
  "REQUEST_DELETE_PROJECT_CATEGORY";
export const RECEIVE_DELETE_PROJECT_CATEGORY =
  "RECEIVE_DELETE_PROJECT_CATEGORY";
export const PROJECT_CATEGORY_DELETE_ERROR = "PROJECT_CATEGORY_DELETE_ERROR";

// Add New User
export const REQUEST_CREATE_NEW_USER = "REQUEST_CREATE_NEW_USER";
export const RECEIVE_CREATE_NEW_USER = "RECEIVE_CREATE_NEW_USER";
export const NEW_USER_CREATE_ERROR = "LANDING_PAGE_CREATE_NEW_USER";
