/**
 * Table
 */
export const REQUEST_TABLE_LIST = "REQUEST_TABLE_LIST";
export const RECEIVE_TABLE_LIST = "RECEIVE_TABLE_LIST";
export const FETCH_TABLE_LIST_FAIL = "FETCH_TABLE_LIST_FAIL";
export const SET_TABLE_PAGE = "SET_TABLE_PAGE";
export const CLEAR_TABLE_LIST = "CLEAR_TABLE_LIST";

/* Dashboard */
export const REQUEST_DASHBOARD_COUNT = "REQUEST_DASHBOARD_COUNT";
export const RECEIVE_DASHBOARD_COUNT = "RECEIVE_DASHBOARD_COUNT";
export const FETCH_DASHBOARDD_COUNT_FAIL = "FETCH_DASHBOARDD_COUNT_FAIL";


// Add New User
export const REQUEST_CREATE_NEW_USER = "REQUEST_CREATE_NEW_USER";
export const RECEIVE_CREATE_NEW_USER = "RECEIVE_CREATE_NEW_USER";
export const NEW_USER_CREATE_ERROR = "LANDING_PAGE_CREATE_NEW_USER";
